"""2026-08-17 — กลอนเหล็กลายเรียบ: base unit โหล -> ตัว (pids 559, 561, 562).

WHY. Put's ruling 2026-08-17: a product's base unit should be its SMALLEST unit
while the catalogue keeps quoting the dozen. That is already what most of the
catalogue does — 195 of 251 `product_price_tiers` rows are '1 โหล' sitting on
products whose `unit_type` is ตัว/อัน/ลูก. The 56 products still carrying
`unit_type='โหล'` are the leftovers and none has a dozen tier row. These three
are batch 1, driven by TikTok needing to sell per piece: the plan would
otherwise list ฿117 against a variant label with no "โหล" in it, when ฿117 buys
twelve bolts.

This is a BASE-UNIT CONVERSION, not a pack/loose split. One product identity
survives and "1 โหล" becomes a derived selling unit held in product_price_tiers.

⚠ NOT `scripts/apply_unit_type_change.py`. That one is DEPRECATED in its own
docstring, and today it would be wrong twice: it hand-writes `stock_levels`
(written before migration 080 added `after_transaction_update`, so it now
DOUBLE-COUNTS — measured: stock 288 instead of 24), and it converts the ledger
but not the prices, leaving `base_sell_price` at the dozen figure against a
per-piece `unit_type`.

── HISTORY OF THIS FILE ────────────────────────────────────────────────────────
v1 ran on the dev DB on 2026-08-17 and was REVERTED after review. It was wrong
in ways worth keeping on the record, because each is a trap this version now
guards:

  * it rewrote the cost-ledger note with a nested replace() on the unit WORDS
    and left the NUMBERS alone, producing "ยอดยกมา 2 ตัว @ 55.00 บาท/ตัว" on a
    row that actually held 24 ตัว @ 4.5833 — FALSE AUDIT EVIDENCE, generated by
    the very step meant to keep the record honest.
  * it asserted no preconditions. It was safe only because these three happened
    to have no sales, purchases, mappings, marketplace rows, promotions or
    formulas — a fact established by hand, in a terminal, and nowhere enforced.
  * its "nothing outside the plan moved" check was
    `WHERE unit_type='ตัว' AND id NOT IN (SELECT id ... WHERE unit_type='ตัว')`,
    which is a contradiction and therefore always returns zero rows. A check
    that cannot fail.
  * it wrote raw SQL, so the price-history rows it created had a blank `source`
    on a deliberate money mutation.

    python3 scripts/2026_08_17_bolt_dozen_to_piece.py --db PATH --threshold keep
    python3 scripts/2026_08_17_bolt_dozen_to_piece.py --db PATH --threshold keep --apply
"""
import argparse
import sqlite3
import sys

RATIO = 12
SOURCE = 'script:2026_08_17_bolt_dozen_to_piece'

# pid: (sku, new per-piece base_sell_price — Put 2026-08-17, ÷12 rounded UP)
PLAN = {
    559: ('BLT-4in-AC', 7.0),
    561: ('BLT-4in-CR', 7.0),
    562: ('BLT-6in-CR', 8.0),
}

# Tables that must hold NOTHING for a target product. Each would need its own
# conversion story, and a blanket x12 would be wrong for every one of them:
# quoted history in dozens, a marketplace qty_per_sale, a pack/unpack formula.
MUST_BE_EMPTY = (
    ('sales_transactions', 'product_id'),
    ('purchase_transactions', 'product_id'),
    ('unit_conversions', 'product_id'),
    ('product_code_mapping', 'product_id'),
    # ⚠ the id column is named differently per table — platform_skus uses
    # internal_product_id, ecommerce_listings plain product_id. Guessing one for
    # both raised "no such column" on the first rehearsal.
    ('platform_skus', 'internal_product_id'),
    ('ecommerce_listings', 'product_id'),
    ('promotions', 'product_id'),
    ('product_price_tiers', 'product_id'),
    ('conversion_formula_inputs', 'product_id'),
)


def preconditions(conn):
    """Refuse on ANY drift from the state this conversion was designed against.

    Runs INSIDE the transaction, before the first write. v1 checked none of
    this: it was correct only because prod happened not to have moved between
    the hand survey and the run.
    """
    bad = []
    for pid, (sku, _) in PLAN.items():
        row = conn.execute(
            "SELECT unit_type, cost_price, base_sell_price, opening_cost "
            "FROM products WHERE id=?", (pid,)).fetchone()
        if row is None:
            bad.append(f"{sku} (pid {pid}) does not exist — wrong DB?")
            continue
        if row[0] == 'ตัว':
            bad.append(f"{sku}: already ตัว — refusing to convert twice")
            continue
        if row[0] != 'โหล':
            bad.append(f"{sku}: unit_type is {row[0]!r}, expected โหล")
        if row[1] <= 0 or row[2] <= 0:
            bad.append(f"{sku}: cost {row[1]} / base {row[2]} — a zero breaks the value check")
        if abs(row[3] - row[1]) > 1e-9:
            bad.append(f"{sku}: opening_cost {row[3]} != cost_price {row[1]}; "
                       f"this script assumes an INITIAL-only product")

        for table, col in MUST_BE_EMPTY:
            n = conn.execute(f"SELECT COUNT(*) FROM {table} WHERE {col}=?", (pid,)).fetchone()[0]
            if n:
                bad.append(f"{sku}: {n} row(s) in {table} — needs its own conversion story")

        txns = conn.execute(
            "SELECT COUNT(*) FROM transactions WHERE product_id=?", (pid,)).fetchone()[0]
        if txns != 1:
            bad.append(f"{sku}: {txns} transactions, expected exactly 1 (the opening ADJUST)")

        cl = conn.execute("SELECT event_type FROM product_cost_ledger WHERE product_id=?",
                          (pid,)).fetchall()
        if len(cl) != 1 or cl[0][0] != 'INITIAL':
            bad.append(f"{sku}: cost ledger is {[r[0] for r in cl]}, expected exactly one INITIAL")
    return bad


def fingerprint_others(conn):
    """Every non-target product's stock and money columns, as one comparable set.

    Replaces v1's tautological 'nothing else moved' check, which could not fail.
    """
    pids = ','.join(str(p) for p in PLAN)
    return conn.execute(
        f"SELECT p.id, p.unit_type, p.cost_price, p.base_sell_price, p.opening_cost, "
        f"       COALESCE(s.quantity, 0) "
        f"  FROM products p LEFT JOIN stock_levels s ON s.product_id = p.id "
        f" WHERE p.id NOT IN ({pids}) ORDER BY p.id").fetchall()


def snapshot(conn):
    out = {}
    for pid in PLAN:
        p = conn.execute("SELECT unit_type, cost_price, base_sell_price, opening_cost, "
                         "low_stock_threshold FROM products WHERE id=?", (pid,)).fetchone()
        s = conn.execute("SELECT quantity FROM stock_levels WHERE product_id=?",
                         (pid,)).fetchone()
        cl = conn.execute("SELECT id, qty_change, unit_cost, note FROM product_cost_ledger "
                          "WHERE product_id=? ORDER BY id", (pid,)).fetchall()
        out[pid] = {'unit_type': p[0], 'cost': p[1], 'base': p[2], 'opening': p[3],
                    'threshold': p[4], 'stock': (s[0] if s else 0), 'ledger': cl}
    return out


def convert(conn, before, threshold_mode):
    for pid, (sku, new_base) in PLAN.items():
        b = before[pid]

        conn.execute(
            "INSERT INTO product_price_tiers (product_id, qty_label, price) VALUES (?,?,?)",
            (pid, '1 โหล', b['base']))

        new_threshold = (b['threshold'] * RATIO if threshold_mode == 'scale'
                         else b['threshold'])
        conn.execute(
            "UPDATE products SET unit_type='ตัว', cost_price=?, opening_cost=?, "
            "base_sell_price=?, low_stock_threshold=? WHERE id=?",
            (b['cost'] / RATIO, b['opening'] / RATIO, new_base, new_threshold, pid))

        # stock_levels is NOT written: after_transaction_update (mig 080) applies
        # the delta itself. Writing it here multiplies twice — measured at 288.
        conn.execute(
            "UPDATE transactions SET quantity_change = quantity_change * ? WHERE product_id=?",
            (RATIO, pid))

        # The note is REBUILT from structured values and APPENDED to the
        # original, never text-substituted. v1's replace() swapped 'โหล' for
        # 'ตัว' and left "2" and "55.00" in place, so the note asserted
        # something the row did not say.
        for lid, qty, unit_cost, note in b['ledger']:
            conn.execute(
                "UPDATE product_cost_ledger SET qty_change = qty_change * ?, "
                "stock_after = stock_after * ?, unit_cost = unit_cost / ?, "
                "wacc_after = wacc_after / ?, note = ? WHERE id=?",
                (RATIO, RATIO, RATIO, RATIO,
                 "{} | แปลงหน่วย 2026-08-17: {:g} โหล @ ฿{:.2f}/โหล → {:g} ตัว @ ฿{:.6f}/ตัว "
                 "({})".format(note or '(ไม่มีหมายเหตุเดิม)', qty, unit_cost,
                               qty * RATIO, unit_cost / RATIO, SOURCE),
                 lid))


def assert_invariants(conn, before, others_before, threshold_mode):
    bad = []
    for pid, (sku, new_base) in PLAN.items():
        b = before[pid]
        row = conn.execute(
            "SELECT unit_type, cost_price, base_sell_price, opening_cost, low_stock_threshold "
            "FROM products WHERE id=?", (pid,)).fetchone()
        stock = conn.execute("SELECT quantity FROM stock_levels WHERE product_id=?",
                             (pid,)).fetchone()[0]

        if row[0] != 'ตัว':
            bad.append(f"{sku}: unit_type {row[0]}")
        if stock != b['stock'] * RATIO:
            bad.append(f"{sku}: stock {stock} != {b['stock'] * RATIO} "
                       f"(a hand-written stock_levels UPDATE doubles this)")

        ledger_sum = conn.execute(
            "SELECT COALESCE(SUM(quantity_change), 0) FROM transactions WHERE product_id=?",
            (pid,)).fetchone()[0]
        if abs(ledger_sum - stock) > 1e-9:
            bad.append(f"{sku}: stock {stock} != SUM(ledger) {ledger_sum}")

        if abs(b['stock'] * b['cost'] - stock * row[1]) > 0.005:
            bad.append(f"{sku}: value {stock * row[1]:.4f} != {b['stock'] * b['cost']:.4f}")
        if abs(row[2] - new_base) > 1e-9:
            bad.append(f"{sku}: base {row[2]} != {new_base}")
        if abs(row[3] - row[1]) > 1e-9:
            bad.append(f"{sku}: opening_cost {row[3]} drifted from cost_price {row[1]}")

        expect_thr = b['threshold'] * RATIO if threshold_mode == 'scale' else b['threshold']
        if row[4] != expect_thr:
            bad.append(f"{sku}: low_stock_threshold {row[4]} != {expect_thr}")

        tiers = conn.execute("SELECT qty_label, price FROM product_price_tiers "
                             "WHERE product_id=?", (pid,)).fetchall()
        if len(tiers) != 1 or tiers[0][0] != '1 โหล' or abs(tiers[0][1] - b['base']) > 1e-9:
            bad.append(f"{sku}: tiers {tiers}, expected one '1 โหล' at {b['base']}")

        # per-EVENT and per-STATE conservation, not just the final total
        for (lid, old_qty, old_cost, _), (nq, nc, ns, nw, note) in zip(
                b['ledger'],
                conn.execute("SELECT qty_change, unit_cost, stock_after, wacc_after, note "
                             "FROM product_cost_ledger WHERE product_id=? ORDER BY id",
                             (pid,)).fetchall()):
            if abs(old_qty * old_cost - nq * nc) > 0.005:
                bad.append(f"{sku}: cost-ledger event value {nq * nc:.4f} != {old_qty * old_cost:.4f}")
            if abs(ns * nw - old_qty * old_cost) > 0.005:
                bad.append(f"{sku}: cost-ledger state value {ns * nw:.4f} != {old_qty * old_cost:.4f}")
            if 'แปลงหน่วย' not in (note or ''):
                bad.append(f"{sku}: cost-ledger note carries no conversion record")
            if 'บาท/โหล' in (note or '') and 'แปลงหน่วย' not in (note or ''):
                bad.append(f"{sku}: cost-ledger note still claims a dozen basis")

        last = conn.execute("SELECT wacc_after FROM product_cost_ledger WHERE product_id=? "
                            "ORDER BY id DESC LIMIT 1", (pid,)).fetchone()[0]
        if abs(last - row[1]) > 1e-9:
            bad.append(f"{sku}: final wacc_after {last} != cost_price {row[1]}")

        hist = conn.execute(
            "SELECT field_name, source FROM product_price_history WHERE product_id=? "
            "AND date(changed_at)=date('now','localtime')", (pid,)).fetchall()
        if not hist:
            bad.append(f"{sku}: no price-history rows written")
        for field, src in hist:
            if src != SOURCE:
                bad.append(f"{sku}: price-history {field} source {src!r}, expected {SOURCE!r}")

    if fingerprint_others(conn) != others_before:
        bad.append("a product OUTSIDE the plan changed")
    return bad


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--db', required=True)
    ap.add_argument('--threshold', required=True, choices=['keep', 'scale'],
                    help="low_stock_threshold is expressed in the base unit, so converting "
                         "changes its physical meaning (10 dozen -> 10 pieces). 'keep' "
                         "leaves the number, 'scale' multiplies it by 12. No default: "
                         "this is Put's call, not the script's.")
    ap.add_argument('--apply', action='store_true')
    a = ap.parse_args()

    conn = sqlite3.connect(a.db, timeout=15)
    conn.execute("PRAGMA busy_timeout=15000")
    conn.execute("PRAGMA foreign_keys=ON")

    conn.execute("BEGIN IMMEDIATE")
    try:
        problems = preconditions(conn)
        if problems:
            conn.rollback()
            print("REFUSED — preconditions not met:")
            for p in problems:
                print("  ✗", p)
            sys.exit(2)

        before = snapshot(conn)
        others_before = fingerprint_others(conn)
        print("BEFORE")
        for pid, b in before.items():
            print(f"  {PLAN[pid][0]:12s} {b['unit_type']:4s} stock {b['stock']:>3} "
                  f"cost {b['cost']:.4f} base {b['base']:.2f} thr {b['threshold']} "
                  f"value {b['stock'] * b['cost']:.2f}")

        # the history trigger reads this in the SAME transaction; a rollback
        # rolls the context back too
        conn.execute("INSERT INTO price_change_source (id, source) VALUES (1, ?) "
                     "ON CONFLICT(id) DO UPDATE SET source = excluded.source", (SOURCE,))
        convert(conn, before, a.threshold)
        conn.execute("INSERT INTO price_change_source (id, source) VALUES (1, NULL) "
                     "ON CONFLICT(id) DO UPDATE SET source = NULL")

        bad = assert_invariants(conn, before, others_before, a.threshold)
    except Exception:
        conn.rollback()
        raise

    if bad:
        conn.rollback()
        print("\nROLLED BACK — invariants failed:")
        for p in bad:
            print("  ✗", p)
        sys.exit(1)

    print("\nAFTER (in-transaction)")
    for pid, (sku, _) in PLAN.items():
        r = conn.execute("SELECT unit_type, cost_price, base_sell_price, low_stock_threshold "
                         "FROM products WHERE id=?", (pid,)).fetchone()
        s = conn.execute("SELECT quantity FROM stock_levels WHERE product_id=?",
                         (pid,)).fetchone()[0]
        n = conn.execute("SELECT note FROM product_cost_ledger WHERE product_id=?",
                         (pid,)).fetchone()[0]
        print(f"  {sku:12s} {r[0]:4s} stock {s:>3} cost {r[1]:.4f} base {r[2]:.2f} "
              f"thr {r[3]} value {s * r[1]:.2f}")
        print(f"       {n}")

    if not a.apply:
        conn.rollback()
        print("\nREHEARSAL — rolled back, nothing written.")
        return

    conn.commit()
    conn.close()

    chk = sqlite3.connect(a.db)
    print("\nCOMMITTED — re-read on a new connection:")
    bad_n = 0
    for pid, (sku, new_base) in PLAN.items():
        r = chk.execute(
            "SELECT p.unit_type, p.cost_price, p.base_sell_price, s.quantity, t.price, "
            "(SELECT COUNT(*) FROM product_price_history h WHERE h.product_id=p.id "
            " AND h.source=?) "
            "FROM products p JOIN stock_levels s ON s.product_id=p.id "
            "LEFT JOIN product_price_tiers t ON t.product_id=p.id WHERE p.id=?",
            (SOURCE, pid)).fetchone()
        ok = (r[0] == 'ตัว' and abs(r[2] - new_base) < 1e-9 and r[5] >= 1)
        bad_n += 0 if ok else 1
        print(f"  {'OK ' if ok else 'BAD'} {sku:12s} {r[0]} stock {r[3]} cost {r[1]:.4f} "
              f"base {r[2]:.2f} tier {r[4]:.2f} history-rows-with-source {r[5]}")
    sys.exit(1 if bad_n else 0)


if __name__ == '__main__':
    main()
