"""Load Express ประวัติการซื้อ (purchase history) into purchase_transactions.

Parses the full-history cp874 file, resolves product_id via product_code_mapping
(same resolver as import_express.py), then INSERTs into purchase_transactions with
synced_to_stock=0.  A batch is logged in import_log.

Rules:
  - Dedup key: (doc_no, bsn_code, line_seq).  line_seq is a 1-based counter
    generated by the parser for cases where the same doc_no + bsn_code appears
    more than once (e.g. split-price RR lines).
    Dedup is enforced IN PYTHON, not by the DB: _existing_dedup_keys() builds a
    set of keys already loaded by prior history batches (import_log.notes LIKE
    'purchase_history%') and this run skips any incoming row whose key is in it.
    The INSERT is a plain INSERT (NOT "INSERT OR IGNORE") and there is NO UNIQUE
    index backing it — so this script is safe to re-run as a whole, but is NOT
    crash-safe mid-run (an exception between INSERT and the set update is not
    protected). One-shot historical backfill; not a recurring import route.
  - GR rows (ใบลดหนี้ / goods returned to supplier) are loaded with a POSITIVE
    qty exactly as Express prints them (there is no return_flag column on
    purchase_transactions). The stock replay treats them as returns and posts
    OUT — see models._sync_bsn_to_stock, which keys on the 'GR' doc-no prefix
    and tags the txn 'BSN ซื้อ-คืน' so WACC averaging skips it.
  - Does NOT call _sync_bsn_to_stock — no stock writes in this phase.
  - Supplier lookup by code (exact match on suppliers.code) or falls back to name.

Usage:
    python scripts/load_purchase_history_20250529.py PATH_TO_CSV [--dry-run]
"""
from __future__ import annotations

import argparse
import sqlite3
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))

import parse_express_purchase_history as p_ph  # noqa: E402

DB_PATH = _HERE.parent / 'inventory_app' / 'instance' / 'inventory.db'


# ── helpers ───────────────────────────────────────────────────────────────────

def _product_id_by_code(conn, code, unit=None):
    """Resolve BSN product_code + unit → product_id via product_code_mapping.

    Mirror of import_express._product_id_by_code: exact (bsn_code, bsn_unit)
    beats bsn_unit='' catch-all.
    """
    if not code:
        return None
    row = conn.execute(
        """
        SELECT m.product_id
          FROM product_code_mapping m
         WHERE m.bsn_code = ?
           AND m.bsn_unit IN (COALESCE(?, ''), '')
           AND m.product_id IS NOT NULL
         ORDER BY (m.bsn_unit = '')
         LIMIT 1
        """,
        (code, unit),
    ).fetchone()
    return row[0] if row else None


def _supplier_id_by_code_or_name(conn, code, name):
    """Look up supplier_id by supplier code first, then by name."""
    if code:
        row = conn.execute('SELECT id FROM suppliers WHERE code = ?', (code,)).fetchone()
        if row:
            return row[0]
    if name:
        row = conn.execute('SELECT id FROM suppliers WHERE name = ?', (name.strip(),)).fetchone()
        if row:
            return row[0]
    return None


def _existing_dedup_keys(conn):
    """Return set of (doc_no, bsn_code, line_seq) already loaded from any
    purchase_history batch (identified by notes LIKE 'purchase_history%').
    """
    rows = conn.execute(
        """
        SELECT pt.doc_no, pt.bsn_code, pt.line_seq
          FROM purchase_transactions pt
          JOIN import_log il ON il.id = pt.batch_id
         WHERE il.notes LIKE 'purchase_history%'
        """
    ).fetchall()
    return {(r[0], r[1], r[2]) for r in rows}


# ── main load ─────────────────────────────────────────────────────────────────

def load(path, dry_run=False):
    """Parse path and load into purchase_transactions.

    Returns (batch_id, rows_inserted, rows_skipped, rows_unmapped).
    """
    # Add line_seq column if absent (backward-compat for older schemas)
    conn = sqlite3.connect(DB_PATH)
    conn.execute('PRAGMA foreign_keys = OFF')

    # Ensure line_seq column exists (may not exist on older schemas) and pair it
    # with its migration bookkeeping. Mig 091's forward .sql is a bare ALTER (no
    # IF NOT EXISTS); if this loader adds the column but '091' is missing from
    # applied_migrations, a later database.run_pending_migrations() re-runs that
    # ALTER and aborts boot with "duplicate column name" (finding #8 on PR #87).
    #
    # ORDER MATTERS: record 091 FIRST (+commit), THEN add the column. Python
    # 3.9's sqlite3 auto-commits DDL (ALTER), so if we altered first and crashed
    # before recording 091 we would recreate the exact column-present/091-absent
    # state that breaks boot. Recording-first means a crash in between leaves
    # 091-recorded/column-absent — which is SAFE: the runner skips mig 091 (no
    # error) and this loader's own guarded ALTER adds the column when it re-runs.
    # line_seq is used only by this history loader, so a transiently-absent
    # column blocks nothing else.
    conn.execute(
        "INSERT OR IGNORE INTO applied_migrations (filename) "
        "VALUES ('091_purchase_transactions_line_seq.sql')"
    )
    conn.commit()
    cols = {row[1] for row in conn.execute('PRAGMA table_info(purchase_transactions)').fetchall()}
    if 'line_seq' not in cols:
        conn.execute('ALTER TABLE purchase_transactions ADD COLUMN line_seq INTEGER NOT NULL DEFAULT 1')
        conn.commit()

    # Parse
    records = list(p_ph.parse_purchase_history(path))
    p_ph.validate(records, path)   # raises on footer mismatch

    if dry_run:
        mapped = sum(1 for r in records if _product_id_by_code(conn, r.product_code, r.unit))
        unmapped = len(records) - mapped
        print(f'[dry-run] parsed={len(records)}  mapped={mapped}  unmapped={unmapped}')
        conn.close()
        return None, 0, 0, unmapped

    # Existing dedup keys from prior history loads
    existing = _existing_dedup_keys(conn)

    # Create import_log batch
    filename = Path(path).name
    cur = conn.execute(
        "INSERT INTO import_log (filename, rows_imported, rows_skipped, notes) "
        "VALUES (?, 0, 0, 'purchase_history')",
        (filename,),
    )
    batch_id = cur.lastrowid

    inserted = 0
    skipped = 0
    unmapped = 0

    for r in records:
        key = (r.doc_no, r.product_code, r.line_seq)
        if key in existing:
            skipped += 1
            continue

        product_id = _product_id_by_code(conn, r.product_code, r.unit)
        if product_id is None:
            unmapped += 1
        supplier_id = _supplier_id_by_code_or_name(conn, r.supplier_code, r.supplier_name)

        conn.execute(
            """
            INSERT INTO purchase_transactions
                (batch_id, date_iso, doc_no, doc_base, product_id, bsn_code,
                 product_name_raw, supplier, supplier_code, qty, unit,
                 unit_price, vat_type, discount, total, net,
                 synced_to_stock, line_seq, supplier_id)
            VALUES
                (?, ?, ?, ?, ?, ?,
                 ?, ?, ?, ?, ?,
                 ?, ?, ?, ?, ?,
                 0, ?, ?)
            """,
            (
                batch_id, r.date_iso, r.doc_no, r.doc_no, product_id, r.product_code,
                r.product_name, r.supplier_name, r.supplier_code, r.qty, r.unit,
                r.unit_price, r.vat_type, r.discount, r.total, r.net,
                r.line_seq, supplier_id,
            ),
        )
        inserted += 1
        existing.add(key)

    # Update import_log counts
    conn.execute(
        "UPDATE import_log SET rows_imported = ?, rows_skipped = ? WHERE id = ?",
        (inserted, skipped, batch_id),
    )
    conn.commit()
    conn.close()
    return batch_id, inserted, skipped, unmapped


def main():
    ap = argparse.ArgumentParser(
        description='Load Express ประวัติการซื้อ into purchase_transactions (synced=0)'
    )
    ap.add_argument('path', type=Path)
    ap.add_argument('--dry-run', action='store_true',
                    help='parse + validate but do not write to DB')
    args = ap.parse_args()

    batch_id, inserted, skipped, unmapped = load(args.path, dry_run=args.dry_run)

    if args.dry_run:
        return

    print(f'OK  batch_id={batch_id}  inserted={inserted}  skipped={skipped}  unmapped={unmapped}')
    print(f'    Rows with product_id=NULL (Phase B): {unmapped}')


if __name__ == '__main__':
    main()
